### ISSUE TITLE
Get scores from Leaderboards

### ISSUE THREAD

**Issue by dwd31415** [dwd31415/GameSharing#15]
This feature can pull scores(if they exits) from a leaderboard.

**Comment by dwd31415** [comment]
Added this feature for iOS with commit e6c7da498b31818a99f3b244b142fd94fea5f666

**Comment by Leandros** [comment]
You forgot to add `currentScore` and `callCppCallback` for Android. It's not building.

**Comment by dwd31415** [comment]
Commit c1ec8b127d266e3051197094b5b881ce3cbebd28 should fix it.
