### ISSUE TITLE
'GKAchievementViewController' is deprecated: first deprecated in iOS 7.0 - Use GKGameCenterViewController instead

### ISSUE THREAD

**Issue by digitalhoax** [dwd31415/GameSharing#20]
Hi, 

will there be an update for the new GKGameCenterViewController?

Cheers!

**Comment by dwd31415** [comment]
Yes, I am planning on updating the source in order to replace all deprecated components.

**Comment by matthewlehew** [comment]
I've initiated a PR on this issue here: https://github.com/dwd31415/GameSharing/pull/22
