### ISSUE TITLE
Authentication window not appearing

### ISSUE THREAD

**Issue by matthewlehew** [dwd31415/GameSharing#23]
Everything about the wrapper works, except the login window doesn't trigger if no user is authenticated. On a test device, there is no visible action when opening the app with no authenticated user.

I don't believe this is due to any kind of login rejection lockout. When signing out of Game Center on the test device and following this sequence: 1) Open app in development, 2) Open other game with GC integration, 3) Open app in development, the login window appears on step 2 but not 3.

This issue occurs both with the standard fork and with the PR I initiated tonight. Any thoughts?

**Comment by dwd31415** [comment]
A very interesting issue. Is there any output if you run your app in debug mode with Xcode connected?

**Comment by matthewlehew** [comment]
No, there's no output. I was able to confirm that the authentication IS returning a viewController by amending GameSharing with an NSLog like so:

    player.authenticateHandler = ^(UIViewController *viewController, NSError *error){
        //Do nothing, for nothing has to be done.
        if (viewController != nil)
        {
            NSLog(@"There is a ViewController");
        }

I also exported the GameKit logs from the device during an authentication attempt, which can be seen here: http://pastebin.com/G92dwL28

One interesting behavior I noticed was that on line 172, it attempt to log me in with my iCloud ID, even though no account was logged in with Game Center. I don't use my iCloud ID for Game Center, I use a pre-iCloud Apple ID that is used for my iTunes store account. Although I don't think that would cause this particular problem since the authentication interface appears on other games.

It's very possible this is a Cocos2d-x issue and not a GameSharing issue.

**Comment by dwd31415** [comment]
Very interesting, I will further investigate this issue.

**Comment by matthewlehew** [comment]
I made the authentication view appear with the following tweak:

    //Do nothing, for nothing has to be done.
        if (viewController != nil)
        {
            AppController* appController = (AppController*) [UIApplication sharedApplication].delegate;
            [appController.viewController presentViewController:viewController animated:YES completion:nil];
        }

However, the console shows the following error when dismissing the view (either through cancelling or entering valid credentials)

`plugin com.apple.GameCenterUI.GameCenterAuthenticateExtension invalidated`

Everything works as expected though, so I don't know how serious that log is.

**Comment by dwd31415** [comment]
That seems to work just fine. I have already added it to GameCenterHelper.mm. To make to work you also have to add this to your AppController:
```
 - (void) gameCenterViewControllerDidFinish:(GKGameCenterViewController *)gameCenterViewController{
    [gameCenterViewController dismissViewControllerAnimated:YES completion:nil];
}

```
