### ISSUE TITLE
Add support for more GPGS operations on android

### ISSUE THREAD

**Issue by dwd31415** [dwd31415/GameSharing#9]

**Comment by spajdo** [comment]
yes plz...

**Comment by dwd31415** [comment]
What features do you have in mind?

**Comment by spajdo** [comment]
Get best score from Services.

Dňa po, 2. mar 2015 15:46 Adrian Dawid <notifications@github.com>
napísal(a):

**Comment by dwd31415** [comment]
This feature will be implemented. Check out Issue #15.

**Comment by dwd31415** [comment]
This issue is closed from now on. If you have a feature request, please post it on gitter: https://gitter.im/dwd31415/GameSharing
